### PR TITLE
Add functionality: gdf_from_bbox.

### PR DESCRIPTION
**Pull request by xgerrmann**

### CODE REVIEW

**Comment by xgerrmann** [comment]
@AtelierLibre Would you like to take a look at this? It contains a functionality which I think will be useful.

**Comment by AtelierLibre** [comment]
@xgerrmann sorry, getting used to working across forks branches etc. I don't have a problem with pulling this in but I think @gboeing needs to comment as he has done a lot of work on tidying up the API and I think if this is to be included it would need to be implemented for the `graph` module as well.

**Comment by gboeing** [comment]
Thanks @xgerrmann.

@AtelierLibre an equivalent `graph_from_bbox` function already exists, so this would help make everything consistent. See [here](https://github.com/gboeing/osmnx/blob/v0.15.1/osmnx/graph.py#L26).

**Comment by AtelierLibre** [comment]
@xgerrmann @gboeing Thanks, I have merged this in.

**Pull request merged**
